app/__init__.py
from routes import blp
from extensions import app


# This function creates the Flask app and registers the Blueprint
def create_app():
    app.config["SECRET_KEY"] = "4f557e8e5eb51bfb7c42"
    app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024

    # Register the Blueprint
    app.register_blueprint(blp)
    # Return the app
    return app

extensions/__init__.py
from flask import Flask, Blueprint

# Create the Flask app
app = Flask(__name__, static_folder='../static', template_folder='../templates')
# Create the Blueprint
blp = Blueprint("routes", __name__)

routes/__init__.py
from extensions import blp
from flask import render_template, redirect, request, url_for, flash
import os
import random


# This is the route for the index page
@blp.route('/', methods=["GET", "POST"])
def index():
    if request.method == "POST":
        if "fileInput" in request.files:
            random_num = random.randint(0000, 9999)
            image = request.files["fileInput"]
            if image.filename != '':
                image.save(os.path.join("static\\images", image.filename))
                return redirect(url_for("routes.display", img=image.filename,
                                        num=random_num))
            flash("Nothing to upload", "danger")
    # Render the index.html template
    return render_template("index.html")


@blp.route("/display/<img>/<num>")
def display(img, num):
    return render_template("display.html", img=img)

templates/display.html
{% extends 'layout.html' %} {% block content %}

<!-- <h4 class="text-center p-2 rounded text-light mt-3 bg-secondary m-auto"
style="width: fit-content;"
>Delete Duplicate</h4> -->
<a href="" class="btn btn-success text-decoration-none d-flex m-auto 
  justify-content-center my-4
  m-auto text-center" style="width: fit-content;">Scan for duplicate</a>

<div class="mt-5" style="width: 70%; margin: auto">
  <img
    src="{{ url_for('static', filename='images/' + img) }}"
    class="img-thumbnail d-flex flex-column m-auto align-items-center justify-content-center"
    style="width: 70%;"
    id="img"
    alt="Image"
  />

</div>

{% endblock content %}

templates/index.html
{% extends 'layout.html' %} {% block content %}

<section
  class="d-flex flex-column m-auto align-items-center justify-content-center"
  style="height: 90vh;"
>
<section style="border: 2px dashed rgb(146, 142, 142);" class="p-5">
  <h4 class="text-muted text-center">UPLOAD A SAMPLE</h4>
  <form
    method="post"
    action="/"
    enctype="multipart/form-data"
    class="d-flex flex-column align-items-center justify-content-center"
    id="upload-form"
  >
    <div style="height: 0px; overflow: hidden">
      <input type="file" id="fileInput" name="fileInput" />
    </div>
    <div>
      <i
        class="fa fa-cloud-download text-info"
        style="font-size: 10rem; cursor: pointer;"
        onclick="chooseFile();"
      ></i>
    </div>
    <input type="submit" value="Upload" class="btn btn-success mt-3" style="display: none;"/>
  </form>
</section>
</section>

<script>
  function chooseFile() {
    document.getElementById("fileInput").click();
  }

  document.getElementById("fileInput").addEventListener("change", function() {
      document.getElementById("upload-form").submit();
  });
</script>

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- The bootstrap libraries -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <!-- fontAwesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <script src="{{ url_for('static', filename='javascript/script.js') }}"></script>
    <title>Delplicate</title>
  </head>
  <body style="background: rgb(0, 0, 0);">

     <!-- Navbar -->
     <nav
     class="navbar navbar-expand-lg navbar-dark py-3 w-100 bg-dark"
     id="navbar"
   >
     <div class="container">
       <a href="#" class="navbar-brand">Delplicate</a>

       <button
         class="navbar-toggler"
         type="button"
         data-bs-toggle="collapse"
         data-bs-target="#navmenu"
       >
         <span class="navbar-toggler-icon"></span>
       </button>

       <div class="collapse navbar-collapse" id="navmenu">
         <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a href="{{ url_for('routes.index') }}" class="nav-link">Upload image</a>
              </li>
           
         </ul>
       </div>
     </div>
   </nav>


    
     <!-- Flash messages -->
 {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div
      class="alert-dismissible fade show mb-4 m-auto small alert alert-{{ category }}"
      role="alert"
      style="height: 3.5rem; transition: 0.6s"
    >
    {% if category=='success' %}
      <p class="small text-center"><i class="fa fas fas fa-check"></i>&nbsp;&nbsp;&nbsp;{{ message }}</p>
      {% else %}
      <p class="small text-center"><i class="fa fas fa-exclamation-triangle"></i>&nbsp;&nbsp;&nbsp;{{ message }}</p>
      {% endif %}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% endif %} {% endwith %}


    {% block content %}

    {% endblock content %}


    <!-- Bootsrap popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
      integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
      crossorigin="anonymous"
    ></script>
  </body>
</html>